spring:
  datasource:
       primary:
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
          driver-class-name: com.mysql.jdbc.Driver
          username: root
          password:
          initialSize: 5
          minIdle: 5
          maxActive: 10
          maxWait: 60000
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000
          validationQuery: SELECT 1 FROM DUAL
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: true
          maxPoolPreparedStatementPerConnectionSize: 20
          filters: stat,wall,slf4j
          connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
          max-wait: 5000
          test-on-borrow: true
       secondary:
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:mysql://localhost:3306/test2?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
          driver-class-name: com.mysql.jdbc.Driver
          username: root
          password:
          initialSize: 5
          minIdle: 5
          maxActive: 10
          maxWait: 60000
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000
          validationQuery: SELECT 1 FROM DUAL
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: true
          maxPoolPreparedStatementPerConnectionSize: 20
          filters: stat,wall,slf4j
          connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
          max-wait: 5000
          test-on-borrow: true


  jpa:
      show-sql: true
      properties:
        hibernate:
           hbm2ddl:
               auto: update #1：value="create-drop" 表示当JPA应用的时候自动创建表，在解应用的时候删除相应的表，这个在做测试的时候比较有用，但在开发过程中不这么用。2：value="create"这个在每次应用启动的时候都会创建数据库表（会删除以前数据库里的数据。。3：value="update" 这个属性的作用是a:每次只会更新数据库表里的信息

  redis:
        database: 2
        hostName: test02-redis.biostime.it
        port: 6379
        timeout: 15000
        pool:
            max-idle: 10
            min-idle: 5
            max-active: 100
            max-wait: 3000
        defaultExpiration: 3600
  devtools:
        restart:
            #热部署生效
          enabled: true
          additional-paths: src/main/java #设置重启的目录
          exclude: WEB-INF/** #classpath目录下的WEB-INF文件夹内容修改不重启。设置WEB-INF下的jsp修改不需要重启

rpc:
    zookeeper:
        sku:
            zookeeperAddress: test-zookeeper01.biostime.it:2181,test-zookeeper02.biostime.it:2181,test-zookeeper03.biostime.it:2181
            namespace: /rpc/merchandise/merger_test
        coupon:
            zookeeperAddress: test-zookeeper01.biostime.it:2181,test-zookeeper02.biostime.it:2181,test-zookeeper03.biostime.it:2181
            namespace: /rpc/coupon/dev
        order:
            zookeeperAddress: test-zookeeper01.biostime.it:2181,test-zookeeper02.biostime.it:2181,test-zookeeper03.biostime.it:2181
            namespace: /rpc/order/finagle
        point:
            zookeeperAddress: test-zookeeper01.biostime.it:2181,test-zookeeper02.biostime.it:2181,test-zookeeper03.biostime.it:2181
            namespace: /rpc/transaction/core
o2o:
    base:
        url: http://appa.mama100.cn

